### PR TITLE
chore: tweaks to development/build environment

### PR DESCRIPTION
**Pull request by bcoe**
1. a babel compile step is run, and compiled assets are published to npm -- so there's no need for `babel-polyfill` and the babel dependencies should only be part of development environment.
2. I've added nyc for test coverage:

screen shot 2017-05-04 at 6 16 38 pm

3. I've added `build` to files, so that that these are the only files present in the published module.

### CODE REVIEW

**Comment by bcoe** [comment]
@dudleycarr I believe this should now be good to go -- tldr; you don't generally want to ship the babel dependencies with your project (they should be dev dependencies) and at publish time you should use them to transpile.

**Comment by dudleycarr** [comment]
@bcoe Thank you for this! I've been working on a slightly different approach. My approach was to use `babel-preset-env` to choose the right amount of transpiling necessary at install time. I want to continue maintaining compatibility with 0.10 and later, but I also believe it's a good idea to polyfill only what's necessary given the user's environment. This approach, however, would require continuing to include babel related packages as dependencies rather than as dev dependencies. Thoughts?

**Comment by bcoe** [comment]
Node 0.10 is end of life, so I've been starting to take the step of dropping it in most of the libraries I maintain -- just dropped it in yargs, which was a hard decision but so far I've seen minimal push back.

However, I can understand the decision to want to continue to support Node 0.10! But, especially for a server side library, I recommend not shipping any of Babel as dependencies; this should all be part of a build step -- I would also recommend only using Babel plugins that shim 0.10 and Node 6 functionality -- this ultimately comes down to preference though.

I don't think feature detection makes sense for a server side library; speaking for npm's use case, I want to know I'm shipping identical code to a server regardless of Node version -- this approach definitely makes sense in the browser mind you, and can be a good pattern.

**Comment by dudleycarr** [comment]
Closing in favor of #145

**Pull request closed without merging**
